### PR TITLE
Bincode no longer exposes ErrorKind::IoError.

### PR DESCRIPTION
**Pull request by brandonedens**

### CODE REVIEW

**Comment by TyOverby** [comment]
This was caused by a breaking change that was accidentally published.  I've yanked that version of the crate, so the build should work again.

**Comment by cmyr** [comment]
@TyOverby Okay that makes sense, I was very confused there for a day. Thank you for the quick fix.

**Comment by trishume** [comment]
@TyOverby do you recommend I still merge this PR or not? It seems that this PR just switches to relying on `bincode` providing a `From` impl for `io::Error` instead of using an explicit variant. What do you recommend we do?

**Comment by TyOverby** [comment]
The PR is no longer necessary, but I think that the code looks nicer 👍

Bincode will not remove the From implementation.

**Pull request merged**
