### PR TITLE
Upgrade `plist` to `1.6`.

### PR DESCRIPTION
**Pull request by CGMossa**

### CODE REVIEW

**Comment by Enselic** [comment]
I'd like to make a 5.2.0 release relatively shortly. Would be nice to include this in the release, if possible. Did you have time yet to look into the test failures?

**Comment by CGMossa** [comment]
Hmm honestly I don't know. Let me rebase and try to run this script locally.
I'm not a Linux / bash script person.

**Comment by CGMossa** [comment]
As far as I can tell, you do regression test, buy looking how sharkp/bat is doing.
But `bat` has this:

```toml
[target.'cfg(target_os = "macos")'.dependencies]
home = "0.5.4"
plist = "1.5.1"
```
for some reason I don't know..

The error message from ci is:
```
error: failed to select a version for `plist`.
    ... required by package `syntect v5.1.0 (/home/runner/work/syntect/syntect/syntect)`
    ... which satisfies path dependency `syntect` of package `bat v0.24.0 (/home/runner/work/syntect/syntect/bat)`
versions that meet the requirements `^1.6` are: 1.6.0

all possible versions conflict with previously selected packages.

  previously selected package `plist v1.5.1`
    ... which satisfies dependency `plist = "^1.5.1"` (locked to 1.5.1) of package `bat v0.24.0 (/home/runner/work/syntect/syntect/bat)`

failed to select a version for `plist` which could resolve this conflict
```

if you got an idea of what I should do, please do message me.

**Comment by Enselic** [comment]
Thank you for checking. I'm afraid I don't have time to look into this. I'll close this PR for now. Of course feel free to reopen if you resume work on this!

**Pull request closed without merging**
