### PR TITLE
Bump to 5.1.0

### PR DESCRIPTION
**Pull request by Enselic**
Draft of release notes:

### Improvements
* Fix how `syntect::util::split_at()` handles multi-byte characters
* Allow case insensitive search for .tmtheme paths
* impl `PartialEq` for `Theme`

### Dependencies
* Upgrade `fancy-regex` to 0.11
* Upgrade `regex-syntax` to 0.7
* Replace `lazy_static` with `once_cell`

### Other
* Change MSRV policy to "last three stable versions"
* Make `Debug` impl of `syntect::highlighting::Color` less verbose

(I have confirmed that this version of syntect passes all bat regression tests: https://github.com/sharkdp/bat/pull/2632)

### CODE REVIEW

**Comment by Enselic** [comment]
Note: Strictly speaking this should be 6.0.0 because we remove public API, but we have previously decided to take the risk. See https://github.com/trishume/syntect/pull/438#pullrequestreview-1035167525 and the rest of the discussion for details.

**Review by trishume — APPROVED** [review]
Thanks for putting this together!

**Comment by trishume** [comment]
How about you try doing the release yourself and let me know if you run into any permissions snags.

**Comment by Enselic** [comment]
Sounds good! Will try.

**Comment by Enselic** [comment]
[Went smoothly!](https://crates.io/crates/syntect/5.1.0) (knock on wood)

**Pull request merged**
