### PR TITLE
Add support for hidden_file_extensions key.

### PR DESCRIPTION
**Pull request by varungandhi-src**
This was introduced in Sublime Text 4.

Addresses one part of https://github.com/trishume/syntect/issues/323.

As I understand it, it doesn't really matter if a file extension is "hidden" or not from the POV of syntax highlighting.

### CODE REVIEW

**Comment by varungandhi-src** [comment]
Is anyone actively working on fixing 323/adding support for the other new features? I didn't see any active PRs related to it, and no one had commented on the issue, but I figured I'd ask first.

**Review by keith-hall — APPROVED** [review]

**Comment by keith-hall** [comment]
> Is anyone actively working on fixing 323/adding support for the other new features?

Not that I know of, no. Iirc I wrote a comment asking for advice on how the API might look like, but had no responses. I did have a quick look at implementing support for popping multiple contexts at once but it wasn't trivial with the current design.

**Review by trishume — APPROVED** [review]
I don't think anyone else is. However note that the real trickiness will be the backtracking support, which I believe will require a complete API overhaul, since currently you can parse in a streaming way since no line can affect a previous line, whereas with backtracking that's no longer true.

I think it might be reasonable to support everything except backtracking though, since there'll be lots of syntaxes which might use some new features but not backtracking.

**Comment by trishume** [comment]
Oh, see the minimum supported rust version CI error, you just need to borrow the array you're iterating.

**Comment by varungandhi-src** [comment]
CI error should be fixed with the latest push.

As for backtracking, thanks for bringing that up. I'd only seen issue 323 and not issue 271, so I hadn't realized that was another potential pain point before bumping to ST4. It looks like a bunch of grammars are [already using the backtracking-related features](https://github.com/trishume/syntect/issues/271#issuecomment-1014137293):

```
Batch File/Batch File.sublime-syntax
C#/C#.sublime-syntax
Git Formats/Git Commit.sublime-syntax
Java/Java.sublime-syntax
JavaScript/JSX.sublime-syntax
JavaScript/JavaScript.sublime-syntax
JavaScript/TSX.sublime-syntax
JavaScript/TypeScript.sublime-syntax
Lua/Lua.sublime-syntax
Markdown/Markdown.sublime-syntax
PHP/PHP Source.sublime-syntax
Python/Python.sublime-syntax
SQL/SQL.sublime-syntax
```

Apart from backtracking, it sounds like adding support for the 4075-specific features, such as syntax inheritance, is not as complicated and shouldn't affect the public API -- is that a fair assessment?

**Comment by jrappen** [comment]
> ... grammars which are using `branch:` ...

also add these pending re-writes from PRs:

- Haskell
- JSON

**Comment by varungandhi-src** [comment]
Could someone please kick-off the PR testing again? The clippy issue should be fixed, and I'm seeing a "First-time contributors need a maintainer to approve running workflows" message.

**Comment by trishume** [comment]
Huh I tried re-running it and the clippy issue happened again. Did you already look into it? Looks like the problem is that the time crate updated past our MSRV, which of course isn't a problem with this PR. Perhaps we need to either bump our MSRV or constrain an older version of the time crate.

**Comment by Enselic** [comment]
I created a PR to bump MSRV along with a motivation of why I believe that is preferred over putting an upper limit on `time`: https://github.com/trishume/syntect/pull/422

**Comment by varungandhi-src** [comment]
Thanks @Enselic, we can retest and land this PR after your PR lands.

**Comment by Enselic** [comment]
@varungandhi-src Could you rebase this so we get a green CI please?

**Comment by varungandhi-src** [comment]
@Enselic rebased and force-pushed.

**Comment by Enselic** [comment]
Since this has been Approved by both Tristan and Keith I will merge this now that CI is green. I took a quick look and the code looked good to me too.

**Pull request merged**
