### PR TITLE
chore: Update pretty_assertions to 0.6

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by trishume** [comment]
I'm guessing if you want to package a version with updated dependencies you might want me to do a release at some point? If so just let me know and I can push one out.

**Comment by ignatenkobrain** [comment]
It would be much appreciated :)

**Comment by trishume** [comment]
I just published v3.1.0 with both the version bumps

**Comment by ignatenkobrain** [comment]
Thank you!

**Pull request merged**
