### PR TITLE
Prepare for 5.0.0: Update CHANGELOG.md and version

### PR DESCRIPTION
**Pull request by Enselic**
Update CHANGELOG.md and bump version to 5.0.0 to make it as easy as possible to release 5.0.0 later when we feel ready (let's again wait a few days at least before we make the release).

The only known thing left to do is to update the 5.0.0 release date in CHANGELOG.md to the date when the release is made.

The updated CHANGLOG.md includes entries for the following open PRs:
* #406
* #407
* #408
* #411

### CODE REVIEW

**Comment by Enselic** [comment]
FWIW, here is all bat regression tests passing with all above open PRs merged to a single temporary branch and used in bat: https://github.com/Enselic/bat/actions/runs/1650806678

Since both syntect CI and bat CI is green for the 5.0.0 changes, it should be safe to at least merge these PRs to syntect git master if they look good code-review-wise. Once they are merged we (read: I) can do additional verification before we publish 5.0.0. Third time's a charm... 🤞

**Comment by Enselic** [comment]
These are probably/potentially easy to fix but semver breaking, so I'd like to look into these too before we release 5.0.0:

* https://github.com/trishume/syntect/issues/94
* https://github.com/trishume/syntect/issues/98
* https://github.com/trishume/syntect/issues/310
* https://github.com/trishume/syntect/issues/385
* https://github.com/trishume/syntect/issues/396

**Comment by trishume** [comment]
I did a pass over all the PRs with just some comments on making the upgrade path smoother.

**Comment by trishume** [comment]
Alright, merged all the open 5.0 PRs, if you want to release now just do any changelog updates and ping me and I'll merge this and release. If you still want to do the Error thing that sounds good to me and I'll wait for that.

**Comment by Enselic** [comment]
Thanks for all reviews!

I just created a PR to fix the Error thing: #420.

Once that PR has landed I also would like to at least make `highlight_line` return a `Result` for #98. I have done some prototyping and it seems pretty straightforward, but I'd like the Error PR to land first.

Once that is done I think we have a pretty solid and future proof API for a 5.0.0 release, and will be happy to update CHANGELOG.md.

**Comment by Enselic** [comment]
Just wanted to give an update. I just created #432 that I believe is the last change we should land before we make a 5.0.0 release.

So if all goes according to plan, we will
1. Review and merge that PR
2. I will update this PR, which we then merge
3. We then make a syntect v5.0.0 release

**Comment by Enselic** [comment]
I have now updated this PR to include the changes in #432. So after
* #432 and
* #409 

have been merged, we SHOULD be able to release syntect 5.0.0. What could go wrong, right? ;)

I have verified that all regression tests in bat passes in a build with those two PRs included: https://github.com/Enselic/bat/actions/runs/2084215734

**Comment by Enselic** [comment]
Merging since https://github.com/trishume/syntect/pull/432 was just merged

**Pull request merged**
